import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
  UserButton,
} from '@clerk/nextjs';
import { ThemeProvider } from '@/components/themes/ThemeProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <ClerkProvider>
      <html lang="en">
        <ThemeProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-100 text-base-content min-h-screen`}
          >
            <header className="bg-base-200 border-b border-base-300">
              <div className="max-w-7xl mx-auto flex justify-end items-center p-4 gap-4 h-16">
                <SignedOut>
                  {/* Using DaisyUI button classes for sign-in/up buttons */}
                  <div className="flex gap-2">
                    <SignInButton mode="modal">
                      <button className="btn btn-sm btn-ghost">Sign in</button>
                    </SignInButton>
                    <SignUpButton mode="modal">
                      <button className="btn btn-sm btn-primary">
                        Sign up
                      </button>
                    </SignUpButton>
                  </div>
                </SignedOut>
                <SignedIn>
                  <UserButton
                    afterSignOutUrl="/"
                    appearance={{
                      elements: {
                        rootBox: 'hover:opacity-80 transition-opacity',
                      },
                    }}
                  />
                </SignedIn>
              </div>
            </header>
            <main className="min-h-[calc(100vh-4rem)]">{children}</main>
          </body>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  );
};

export default RootLayout;
